CREATE TABLE SCHEMA_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER NOT NULL,
		OWNER_PID INTEGER NOT NULL,
		RIGHTS SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		SCHEMA_DEFN_PID INTEGER NOT NULL,
		DESCRIPTION VARCHAR(300) NOT NULL,
		VERSION_NAME VARCHAR(160) NOT NULL,
		MAIN_PCKG_KEY SMALLINT NOT NULL
	);

CREATE TABLE PACKAGES (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER NOT NULL,
		OWNER_PID INTEGER NOT NULL,
		RIGHTS SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		PACKAGE_PID INTEGER NOT NULL,
		DESCRIPTION VARCHAR(300),
		VERSON_NAME VARCHAR(160),
		PARENT_SCHEMA_KEY SMALLINT,
		IS_MAIN_PCKG BOOLEAN
	);

CREATE TABLE PLUGINS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER NOT NULL,
		OWNER_PID INTEGER NOT NULL,
		RIGHTS SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		PLUGIN_PID INTEGER NOT NULL,
		DESCRIPTION VARCHAR(300),
		VERSON_NAME VARCHAR(160),
		PARENT_PCKG_KEY SMALLINT,
		IS_MAIN_PLUGIN BOOLEAN
	);

CREATE TABLE TABLE_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER NOT NULL,
		OWNER_PID INTEGER NOT NULL,
		RIGHTS SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		TABLE_DEFN_PID INTEGER NOT NULL,
		PLUGIN_PID SMALLINT,
		LAST_RECD_PID INTEGER,
		DESCRIPTION VARCHAR(300),
		VERSION_NAME VARCHAR(160),
		SQL_NAME VARCHAR(30),
		IS_ADMIN BOOLEAN,
		IS_ENTITY BOOLEAN,
		IS_DEFN BOOLEAN,
		NUM_FLAGS SMALLINT,
		FLAG_KEY SMALLINT,
		NUM_NOTEPADS SMALLINT,
		NOTEPAD_KEY SMALLINT,
		BASE_ENITYY_KEY SMALLINT
	);

CREATE TABLE RECORD_VALIDS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER NOT NULL,
		OWNER_PID INTEGER NOT NULL,
		RIGHTS SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		RECORD_VALID_PID INTEGER NOT NULL,
		PLUGIN_ID INTEGER,
		RECORD_VALID_KEY SMALLINT,
		RECORD_RULE_KEY SMALLINT
	);

CREATE TABLE INDEX_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER NOT NULL,
		OWNER_PID INTEGER NOT NULL,
		RIGHTS SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		INDEX_DEFN_PID INTEGER NOT NULL,
		PARENT_TABLE_KEY SMALLINT,
		INDEX_KEY SMALLINT,
		SQL_INDEX_NAME VARCHAR(30),
		SQL_INDEX_DEFN VARCHAR(300),
		IS_PRIMARY BOOLEAN
	);

CREATE TABLE FIELD_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER NOT NULL,
		OWNER_PID INTEGER NOT NULL,
		RIGHTS SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		FIELD_DEFN_PID INTEGER NOT NULL,
		FIELD_TYPE_KEY SMALLINT,
		VERSION_NAME VARCHAR(300),
		SQL_NAME VARCHAR(30),
		SQL_TYPE VARCHAR(30),
		DATA_TYPE_KEY SMALLINT,
		ENCODE_TYPE_KEY SMALLINT,
		FIELD_FORMAT_KEY SMALLINT,
		FIELD_VALID_KEY SMALLINT,
		FIELD_RECENT_PID INTEGER,
		MAX_RECENT SMALLINT,
		MAX_FIXED SMALLINT,
		LEFT_FIELD_PID INTEGER,
		RIGHT_FIELD_PID INTEGER,
		HAS_AUTO_FILLIN BOOLEAN
	);

CREATE TABLE FIELD_TYPES (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER NOT NULL,
		OWNER_PID INTEGER NOT NULL,
		RIGHTS SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		FIELD_TYPE_PID INTEGER NOT NULL, 
				DATA_TYPE_PID SMALLINT,
		IN_FORMAT_PID INTEGER,
		OUT_FORMAT_KEY SMALLINT,
		MIN_INTEGER BIGINT,
		MAX_INTEGER BIGINT,
		MIN_FLOAT DOUBLE,
		MAX_FLOAT DOUBLE,
		MAX_STRING_LEN INTEGER,
		MIN_STRING_LEN INTEGER,
		ENCODING_KEY SMALLINT
	);

CREATE TABLE FIELD_DATA_TYPES (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER NOT NULL,
		OWNER_PID INTEGER NOT NULL,
		RIGHTS SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		FIELD_DATA_TYPE_PID INTEGER NOT NULL
	);

CREATE TABLE FIELD_FORMATS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER NOT NULL,
		OWNER_PID INTEGER NOT NULL,
		RIGHTS SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		FIELD_FORMAT_PID INTEGER NOT NULL
	);

CREATE TABLE FIELD_VALIDS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER NOT NULL,
		OWNER_PID INTEGER NOT NULL,
		RIGHTS SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		FIELD_VALID_PID INTEGER NOT NULL,
				FIELD_RULE_KEY SMALLINT
	);

CREATE TABLE FIELD_RECENTS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER NOT NULL,
		OWNER_PID INTEGER NOT NULL,
		RIGHTS SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		FIELD_RECENT_PID INTEGER NOT NULL,
		TABLE_KEY SMALLINT,
		FIELD_PID SMALLINT,
		RECENT01_PID INTEGER,
		RECENT02_PID INTEGER,
		RECENT03_PID INTEGER,
		RECENT04_PID INTEGER,
		RECENT05_PID INTEGER,
		RECENT06_PID INTEGER,
		RECENT07_PID INTEGER,
		RECENT08_PID INTEGER,
		RECENT09_PID INTEGER,
		RECENT10_PID INTEGER,
		RECENT11_PID INTEGER,
		RECENT12_PID INTEGER,
		RECENT13_PID INTEGER,
		RECENT14_PID INTEGER,
		RECENT15_PID INTEGER,
		FIXED01_PID INTEGER,
		FIXED02_PID INTEGER,
		FIXED03_PID INTEGER,
		FIXED04_PID INTEGER,
		FIXED05_PID INTEGER
	);

CREATE TABLE PROJECTS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER NOT NULL,
		OWNER_PID INTEGER NOT NULL,
		RIGHTS SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		PROJECT_PID INTEGER NOT NULL,
				COMMENCED TIMESTAMP
	);

CREATE TABLE DISPLAY_TYPES (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER NOT NULL,
		OWNER_PID INTEGER NOT NULL,
		RIGHTS SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		DISPLAY_TYPE_PID INTEGER NOT NULL,
				SCREEN_COUNT SMALLINT,
		WIDTH INTEGER,
		HEIGHT INTEGER,
		HAS_KEYBOARD BOOLEAN,
		TOUCH_SCREEN_ BOOLEAN,
		AUTO_ROTATE BOOLEAN,
		HAS_INTERNET BOOLEAN,
		HAS_SERVER BOOLEAN
	);

CREATE TABLE SESSIONS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER NOT NULL,
		OWNER_PID INTEGER NOT NULL,
		RIGHTS SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		SESSION_PID INTEGER NOT NULL,
		PROJECT_PID INTEGER,
		USER_PID INTEGER,
		TIME_OPENED TIMESTAMP,
		TIME_CLOSED TIMESTAMP,
		COMMIT_NUM INTEGER
	);

CREATE TABLE COMMIT_LOGS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER NOT NULL,
		OWNER_PID INTEGER NOT NULL,
		RIGHTS SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		COMMIT_LOG_PID INTEGER NOT NULL,
		COMMENCE TIMESTAMP,
		COMPLETED TIMESTAMP,
		USER_PID INTEGER,
		CLIENT_PID INTEGER,
		NUM_TABLES SMALLINT
	);

CREATE TABLE COMMIT_ITEMS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER NOT NULL,
		OWNER_PID INTEGER NOT NULL,
		RIGHTS SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		COMMIT_ITEM_PID INTEGER NOT NULL,
		PARENT_CMT_PID INTEGER,
		TABLE_PID SMALLINT,
		RECORD_PID INTEGER,
		PREV_CMT_PID INTEGER
	);

CREATE TABLE USERS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER NOT NULL,
		OWNER_PID INTEGER NOT NULL,
		RIGHTS SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		USER_PID INTEGER NOT NULL,
		LOGON_NAME VARCHAR(100),
		USER_NAME VARCHAR(100),
		PASSWORD VARCHAR(100),
		EMAIL VARCHAR(100),
		USER_TYPE_PID INTEGER,
		USER_GROUP_PID INTEGER
	);

CREATE TABLE USER_GROUPS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER NOT NULL,
		OWNER_PID INTEGER NOT NULL,
		RIGHTS SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		USER_GROUP_PID INTEGER NOT NULL
	);

CREATE TABLE USER_TYPES (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER NOT NULL,
		OWNER_PID INTEGER NOT NULL,
		RIGHTS SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		USER_TYPE_PID INTEGER NOT NULL,
				POOR_EYESIGHT BOOLEAN,
		IS_COLORBLIND BOOLEAN,
		MIN_MOUSE_USE BOOLEAN
	);

CREATE TABLE USER_MESSAGES (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER NOT NULL,
		OWNER_PID INTEGER NOT NULL,
		RIGHTS SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		USER_MESSAGE_PID INTEGER NOT NULL,
		FROM_USER_PID INTEGER,
		TO_USER_PID INTEGER,
		TIME_SENT TIMESTAMP,
		MESSAGE VARCHAR(300),
		IS_READ BOOLEAN,
		IS_ACKD BOOLEAN,
		REPLIED BOOLEAN
	);

CREATE TABLE PROJECT_SERVERS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER NOT NULL,
		OWNER_PID INTEGER NOT NULL,
		RIGHTS SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		PROJECT_SERVER_PID INTEGER NOT NULL,
		LOGON_NAME VARCHAR(100),
		USER_NAME VARCHAR(100),
		PASSWORD VARCHAR(100),
		EMAIL VARCHAR(100),
		USER_GROUP_PID SMALLINT
	);

CREATE TABLE ENTITY_TAG_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER NOT NULL,
		OWNER_PID INTEGER NOT NULL,
		RIGHTS SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		ENTITY_TAG_DEFN_PID INTEGER NOT NULL,
		PLUGIN_PID SMALLINT,
				IS_DEFAULT BOOLEAN
	);

CREATE TABLE ENTITY_NAME_TAG_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER NOT NULL,
		OWNER_PID INTEGER NOT NULL,
		RIGHTS SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		ENTITY_NAME_TAG_DEFN_PID INTEGER NOT NULL,
		PLUGIN_PID SMALLINT,
				IS_DEFAULT BOOLEAN
	);

CREATE TABLE TAG_GROUP_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER NOT NULL,
		OWNER_PID INTEGER NOT NULL,
		RIGHTS SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		TAG_GROUP_DEFN_PID INTEGER NOT NULL,
		PLUGIN_PID SMALLINT,
		MAJOR_GRP_KEY SMALLINT,
		MINOR_GRP_KEY SMALLINT,
		IS_DEFAULT BOOLEAN
	);

CREATE TABLE TAG_RULE_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER NOT NULL,
		OWNER_PID INTEGER NOT NULL,
		RIGHTS SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		TAG_RULE_DEFN_PID INTEGER NOT NULL,
		PLUGIN_PID SMALLINT,
		IS_DEFAULT BOOLEAN
	);

CREATE TABLE THEME_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER NOT NULL,
		OWNER_PID INTEGER NOT NULL,
		RIGHTS SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		THEME_DEFN_PID INTEGER NOT NULL,
		PLUGIN_PID SMALLINT,
		MAJOR_THEME_KEY SMALLINT,
		MINOR_THEME_KEY SMALLINT,
		IS_DEFAULT BOOLEAN
	);

CREATE TABLE LIFE_PHASE (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER NOT NULL,
		OWNER_PID INTEGER NOT NULL,
		RIGHTS SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		LIFE_PHASE_PID INTEGER NOT NULL,
		PLUGIN_PID SMALLINT,
		IS_DEFAULT BOOLEAN
	);

CREATE TABLE ENCODING_TYPE_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER NOT NULL,
		OWNER_PID INTEGER NOT NULL,
		RIGHTS SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		ENCODING_TYPE_DEFN_PID INTEGER NOT NULL,
		IS_DEFAULT BOOLEAN
	);

CREATE TABLE TEMPLATE_TYPE_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		TEMPLATE_TYPE_DEFNS_PID INTEGER NOT NULL,
		VISIBLE_ID INTEGER NOT NULL,
		OWNER_PID INTEGER NOT NULL,
		RIGHTS SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		TEMPLATE_TYPE_DEFN_PID INTEGER NOT NULL
	);

CREATE TABLE PUBLISH_TYPE_TRANS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER NOT NULL,
		OWNER_PID INTEGER NOT NULL,
		RIGHTS SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		PUBLISH_TYPE_TRAN_PID INTEGER NOT NULL
	);

CREATE TABLE SENTENCE_TYPE_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER NOT NULL,
		OWNER_PID INTEGER NOT NULL,
		RIGHTS SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		SENTENCE_TYPE_DEFN_PID INTEGER NOT NULL,
		REQUESTER_TYPE_TBL SMALLINT,
		REQUESTER_TYPE_PID SMALLINT,
		IS_DFLT_SENTENCE BOOLEAN
	);

CREATE TABLE NAMED_MEMO_TYPES (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER NOT NULL,
		OWNER_PID INTEGER NOT NULL,
		RIGHTS SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		NAMED_MEMO_TYPE_PID INTEGER NOT NULL,
		PARENT_TAG_TYPE_KEY SMALLINT,
		PARENT_TAG_TYPE_PID SMALLINT,
		NAMED_MEMO_KEY INTEGER,
		REMINDER_PID INTEGER,
		SHOW BOOLEAN
	);

CREATE TABLE NAME_STYLE_TYPE_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER NOT NULL,
		OWNER_PID INTEGER NOT NULL,
		RIGHTS SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		NAME_STYLE_TYPE_DEFN_PID INTEGER NOT NULL,
		ENTITY_TYPE_KEY SMALLINT,
		NAME_ELMNTS_INPUT_KEY SMALLINT,
		NAME_OUT_TEMPLATES_KEY SMALLINT
	);

CREATE TABLE NAME_ELMNT_INPUT_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER NOT NULL,
		OWNER_PID INTEGER NOT NULL,
		RIGHTS SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		NAME_ELMNT_INPUT_DEFN_PID INTEGER NOT NULL,
		ENTITY_TYPE_TBL SMALLINT,
		NAME_STYLE_PID SMALLINT,
		NAME_ELMNT_TYPE_KEY SMALLINT,
		DATA_TYPE_KEY SMALLINT,
		INPUT_ORDER SMALLINT,
		FIELD_VALID_KEY SMALLINT,
		LEFT_FIELD_ELMNT_PID SMALLINT,
		RIGHT_FIELD_ELMNT_PID SMALLINT
	);

CREATE TABLE NAME_ELMNT_TYPE_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER NOT NULL,
		OWNER_PID INTEGER NOT NULL,
		RIGHTS SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		NAME_ELMNT_TYPE_DEFN_PID INTEGER NOT NULL,
		ENTITY_TYPE_KEY SMALLINT,
		DATA_TYPE_KEY SMALLINT,
		FIELD_VALID_KEY SMALLINT
	);

CREATE TABLE NAME_TEMPLATE_TYPES (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER NOT NULL,
		OWNER_PID INTEGER NOT NULL,
		RIGHTS SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		NAME_ELMNT_TYPE_DEFN_PID INTEGER NOT NULL,
		ENTITY_TYPE_KEY SMALLINT,
		OUT_TEMPLATE_TYPE_KEY SMALLINT,
		SORTING_ONLY BOOLEAN,
		IS_MANDATORY BOOLEAN
	);

CREATE TABLE NAME_OUT_TEMPLATES (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER NOT NULL,
		OWNER_PID INTEGER NOT NULL,
		RIGHTS SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		NAME_OUT_TEMPLATE_PID INTEGER NOT NULL,
		ENTITY_TYPE_KEY SMALLINT,
		ENCODING_KEY SMALLINT,
		SORTING_ONLY BOOLEAN
	);

CREATE TABLE LANGUAGES (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER NOT NULL,
		OWNER_PID INTEGER NOT NULL,
		RIGHTS SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		LANGUAGE_PID INTEGER NOT NULL,
		LANGUAGE_CODE VARCHAR(4),
		LANGUAGE_NAME VARCHAR(60),
		IS_GUI_LANG BOOLEAN,
		IS_DATA_LANG BOOLEAN
	);

CREATE TABLE LANGUAGE_USES (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER NOT NULL,
		OWNER_PID INTEGER NOT NULL,
		RIGHTS SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		LANGUAGE_USE_PID INTEGER NOT NULL,
		GUI_LANGUAGE VARCHAR(4),
		DATA1_LANGUAGE VARCHAR(4),
		DATA2_LANGUAGE VARCHAR(4),
		REPORT_LANGUAGE VARCHAR(4),
		DFLT_LANGUAGE VARCHAR(4)
	);

CREATE TABLE LANGUAGE_NAME_TRANS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER NOT NULL,
		OWNER_PID INTEGER NOT NULL,
		RIGHTS SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		LANGUAGE_NAME_TRAN_PID INTEGER NOT NULL,
		TO_LANGUAGE VARCHAR(4),
		FROM_LANGUAGE VARCHAR(4),
		TRANSLATION VARCHAR(60)
	);

CREATE TABLE LABEL_TRANS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER NOT NULL,
		OWNER_PID INTEGER NOT NULL,
		RIGHTS SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		LABEL_TRAN_PID INTEGER NOT NULL,
		TABLE_PID SMALLINT,
		FIELD_PID SMALLINT,
		RECORD_PID INTEGER,
		SORT SMALLINT,
		LANG_CODE VARCHAR(4),
		NAME VARCHAR(160),
		DESCRIPTION VARCHAR(300),
		ABBREV VARCHAR(60)
	);

CREATE TABLE GUI_MAPPED_TRANS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER NOT NULL,
		OWNER_PID INTEGER NOT NULL,
		RIGHTS SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		GUI_MAPPED_TRAN_PID INTEGER NOT NULL,
		PLUGIN_PID SMALLINT,
		ELEMENT_PID SMALLINT,
		TRANS_KEY SMALLINT,
		SHARED SMALLINT
	);

CREATE TABLE GUI_20_DICT_TRANS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER NOT NULL,
		OWNER_PID INTEGER NOT NULL,
		RIGHTS SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		GUI_20_DICT_TRAN_PID INTEGER NOT NULL,
		PLUGIN_PID SMALLINT,
		SHARED SMALLINT,
		LANG_CODE VARCHAR(4),
		TRANSLATION VARCHAR(20)
	);

CREATE TABLE GUI_60_DICT_TRANS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER NOT NULL,
		OWNER_PID INTEGER NOT NULL,
		RIGHTS SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		GUI_60_DICT_TRAN_PID INTEGER NOT NULL,
		PLUGIN_PID SMALLINT,
		SHARED SMALLINT,
		LANG_CODE VARCHAR(4),
		TRANSLATION VARCHAR(60)
	);

CREATE TABLE GUI_160_DICT_TRANS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER NOT NULL,
		OWNER_PID INTEGER NOT NULL,
		RIGHTS SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		GUI_160_DICT_TRAN_PID INTEGER NOT NULL,
		PLUGIN_PID SMALLINT,
		SHARED SMALLINT,
		LANG_CODE VARCHAR(4),
		TRANSLATION VARCHAR(160)
	);

CREATE TABLE GUI_400_DICT_TRANS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER NOT NULL,
		OWNER_PID INTEGER NOT NULL,
		RIGHTS SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		GUI_400_DICT_TRAN_PID INTEGER NOT NULL,
		PLUGIN_PID SMALLINT,
		SHARED SMALLINT,
		LANG_CODE VARCHAR(4),
		TRANSLATION VARCHAR(400)
	);

CREATE TABLE DATA_20_DICT_TRANS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER NOT NULL,
		OWNER_PID INTEGER NOT NULL,
		RIGHTS SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		DATA_20_DICT_TRAN_PID INTEGER NOT NULL,
		PLUGIN_PID SMALLINT,
		OBJECT_KEY SMALLINT,
		OBJECT_PID INTEGER,
		FIELD_PID INTEGER,
		LANG_CODE VARCHAR(4),
		TRANS VARCHAR(20)
	);

CREATE TABLE DATA_60_DICT_TRANS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER NOT NULL,
		OWNER_PID INTEGER NOT NULL,
		RIGHTS SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		DATA_60_DICT_TRAN_PID INTEGER NOT NULL,
		PLUGIN_PID SMALLINT,
		OBJECT_KEY SMALLINT,
		OBJECT_PID INTEGER,
		FIELD_PID INTEGER,
		LANG_CODE VARCHAR(4),
		TRANS VARCHAR(60)
	);

CREATE TABLE DATA_160_DICT_TRANS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER NOT NULL,
		OWNER_PID INTEGER NOT NULL,
		RIGHTS SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		DATA_160_DICT_TRAN_PID INTEGER NOT NULL,
		PLUGIN_PID SMALLINT,
		OBJECT_KEY SMALLINT,
		OBJECT_PID INTEGER,
		FIELD_PID INTEGER,
		LANG_CODE VARCHAR(4),
		TRANS VARCHAR(160)
	);

CREATE TABLE DATA_400_DICT_TRANS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER NOT NULL,
		OWNER_PID INTEGER NOT NULL,
		RIGHTS SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		PLUGIN_PID SMALLINT,
		DATA_400_DICT_TRAN_PID INTEGER NOT NULL,
		OBJECT_KEY SMALLINT,
		OBJECT_PID INTEGER,
		FIELD_PID INTEGER,
		LANG_CODE VARCHAR(4),
		TRANS VARCHAR(400)
	);

CREATE TABLE ROLE_NAME_TRANS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER,
		OWNER_PID INTEGER,
		RIGHTS SMALLINT,
		COMMIT_PID INTEGER,
		ROLE_NAME_TRAN_PID INTEGER NOT NULL,
		PLUGIN_PID SMALLINT,
		TAG_KEY SMALLINT,
		LANG_CODE VARCHAR(4),
		ROLE VARCHAR(60)
	);

CREATE TABLE ROLE_PAIR_NAME_TRANS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER,
		OWNER_PID INTEGER,
		RIGHTS SMALLINT,
		COMMIT_PID INTEGER,
		ROLE_PAIR_NAME_TRAN_PID INTEGER NOT NULL,
		PLUGIN_PID SMALLINT,
		TAG_KEY SMALLINT,
		LANG_CODE VARCHAR(4),
		ROLE_A_TO_B VARCHAR(60),
		ROLE_B_TO_A VARCHAR(60)
	);

CREATE TABLE REMINDER_TRANS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER,
		OWNER_PID INTEGER,
		RIGHTS SMALLINT,
		COMMIT_PID INTEGER,
		REMINDER_TRAN_PID INTEGER NOT NULL,
		PLUGIN_PID SMALLINT,
		SCREEN_KEY SMALLINT,
		SCREEN_PID SMALLINT,
		LANG_CODE VARCHAR(4),
		ENCODING_KEY SMALLINT,
		REMINDER VARCHAR(400)
	);

CREATE TABLE MESSAGES_TRANS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER,
		OWNER_PID INTEGER,
		RIGHTS SMALLINT,
		COMMIT_PID INTEGER,
		MESSAGES_TRAN_PID INTEGER NOT NULL,
		PLUGIN_PID SMALLINT,
		REQUESTER_KEY SMALLINT,
		REQUESTER_PID INTEGER,
		ENCODING_KEY SMALLINT,
		LANG_CODE VARCHAR(4),
		MESSAGE VARCHAR(400),
		IS_ERROR BOOLEAN
	);

CREATE TABLE SENTENCE_TRANS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		SENTENCE_TRANS_PID INTEGER NOT NULL,
		VISIBLE_ID INTEGER,
		OWNER_PID INTEGER,
		RIGHTS SMALLINT,
		COMMIT_PID INTEGER,
		SENTENCE_TRAN_PID INTEGER NOT NULL,
		PLUGIN_PID SMALLINT,
		REQUESTER_KEY SMALLINT,
		REQUESTER_PID INTEGER,
		SENTENCE_TYPE_KEY SMALLINT,
		ENCODING_KEY SMALLINT,
		SENTENCE_TYPE_PID SMALLINT,
		LANG_CODE VARCHAR(4),
		SENTENCE VARCHAR(1000)
	);

CREATE TABLE NAMED_MEMO_TRANS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER,
		OWNER_PID INTEGER,
		RIGHTS SMALLINT,
		COMMIT_PID INTEGER,
		NAMED_MEMO_TRAN_PID INTEGER NOT NULL,
		PLUGIN_PID SMALLINT,
		REQUESTER_KEY SMALLINT,
		REQUESTER_PID INTEGER,
		ENCODING_KEY SMALLINT,
		MEMO_TYPE_KEY SMALLINT,
		LANG_CODE VARCHAR(4),
		MEMO CLOB(2147483647)
	);

CREATE TABLE OUTPUT_TEMPLATE_TRANS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER,
		OWNER_PID INTEGER,
		RIGHTS SMALLINT,
		COMMIT_PID INTEGER,
		OUTPUT_TEMPLATE_TRAN_PID INTEGER NOT NULL,
		PLUGIN_PID SMALLINT,
		NAME_STYLE_KEY SMALLINT,
		TEMPLATE_TYPE_KEY SMALLINT,
		PUBLISH_TYPE_KEY SMALLINT,
		ENCODING_KEY SMALLINT,
		LANG_CODE VARCHAR(4),
		TEMPLATE VARCHAR(4000)
	);

CREATE TABLE FLAG_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER,
		OWNER_PID INTEGER,
		RIGHTS SMALLINT,
		COMMIT_PID INTEGER,
		FLAG_DEFN_PID INTEGER NOT NULL,
		PARENT_OBJ_KEY SMALLINT,
		STATES SMALLINT,
		DFLT_STATE SMALLINT,
		DISP_ORDER SMALLINT,
		SHOW BOOLEAN,
		ALLOW_COLLECTIONS BOOLEAN
	);

CREATE TABLE FLAG_STATE_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER,
		OWNER_PID INTEGER,
		RIGHTS SMALLINT,
		COMMIT_PID INTEGER,
		FLAG_STATE_DEFN_PID INTEGER NOT NULL,
		PARENT_FLAG_PID SMALLINT,
		STATE_VALUE SMALLINT,
		DISP_ORDER SMALLINT,
		COLLECTION_KEY INTEGER,
		COLLECTION_PID INTEGER
	);

CREATE TABLE NOTEPAD_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER,
		OWNER_PID INTEGER,
		RIGHTS SMALLINT,
		COMMIT_PID INTEGER,
		NOTEPAD_DEFN_PID INTEGER NOT NULL,
		PARENT_OBJ_KEY SMALLINT,
		LENGTH SMALLINT,
		FIELD_TYPE_KEY SMALLINT,
		NO_SHOW BOOLEAN
	);

CREATE TABLE GUI_LANGUAGES (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER,
		OWNER_PID INTEGER,
		RIGHTS SMALLINT,
		COMMIT_PID INTEGER,
		GUI_LANGUAGE_PID INTEGER NOT NULL,
		GUI_LANGUAGE VARCHAR(4),
		DATA1_LANGUAGE VARCHAR(4),
		DATA2_LANGUAGE VARCHAR(4),
		REPORT_LANGUAGE VARCHAR(4),
		DFLT_LANGUAGE VARCHAR(4)
	);

CREATE TABLE GUI_LANGUAGE_NAMES (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		GUI_LANGUAGE_NAMES_PID INTEGER NOT NULL,
		VISIBLE_ID INTEGER,
		OWNER_PID INTEGER,
		RIGHTS SMALLINT,
		COMMIT_PID INTEGER,
		GUI_LANGUAGE_NAME_PID INTEGER NOT NULL,
		FROM_LANGUAGE VARCHAR(4),
		TO_LANGUAGE VARCHAR(4),
		TRANSLATION VARCHAR(60)
	);

CREATE TABLE VIEWPOINT_CONFIGS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER,
		OWNER_PID INTEGER,
		RIGHTS SMALLINT,
		COMMIT_PID INTEGER,
		VIEWPOINT_CONFIG_PID INTEGER NOT NULL,
		VIEWPOINT_TYPE_KEY SMALLINT,
		DISPLAY_TYPE_PID SMALLINT,
		LEFT_EDGE INTEGER,
		TOP_EDGE INTEGER,
		WIDTH INTEGER,
		HEIGHT INTEGER,
		LAST_OPENED TIMESTAMP,
		IS_DEFAULT BOOLEAN
	);

CREATE TABLE VIEWPOINT_ELEMENTS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER,
		OWNER_PID INTEGER,
		RIGHTS SMALLINT,
		COMMIT_PID INTEGER,
		VIEWPOINT_ELEMENT_PID INTEGER NOT NULL,
		VIEWPOINT_PID INTEGER,
		SCREEN_CONFIG_PID SMALLINT,
		IS_MASTER BOOLEAN,
		IS_SECOND_COPY BOOLEAN,
		AUTO_UPDATE BOOLEAN,
		SHOW_ON_OPEN BOOLEAN
	);

CREATE TABLE GUI_SCREEN_CONFIGS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER,
		OWNER_PID INTEGER,
		RIGHTS SMALLINT,
		COMMIT_PID INTEGER,
		GUI_SCREEN_CONFIG_PID INTEGER NOT NULL,
		PLUGIN_PID SMALLINT,
		IS_CONTAINER BOOLEAN,
		HAS_STRING BOOLEAN
	);

CREATE TABLE GUI_SCREENS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER,
		OWNER_PID INTEGER,
		RIGHTS SMALLINT,
		COMMIT_PID INTEGER,
		GUI_SCREEN_PID INTEGER NOT NULL,
		PLUGIN_PID SMALLINT,
		TOP_ELEMENT SMALLINT
	);

CREATE TABLE GUI_ELEMENTS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER,
		OWNER_PID INTEGER,
		RIGHTS SMALLINT,
		COMMIT_PID INTEGER,
		GUI_ELEMENT_PID INTEGER NOT NULL,
		PLUGIN_PID SMALLINT,
		GUI_SCREEN_PID SMALLINT,
		CONTAINER_PID SMALLINT,
		ELEMENT_TYPE_PID INTEGER,
		TRANSLATION_PID INTEGER
	);

CREATE TABLE GUI_ELEMENT_SETTINGS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER,
		OWNER_PID INTEGER,
		RIGHTS SMALLINT,
		COMMIT_PID INTEGER,
		GUI_ELEMENT_SETTING_PID INTEGER NOT NULL,
		PLUGIN_PID SMALLINT,
		GUI_ELEMENT_PID INTEGER,
		IS_CONTAINER BOOLEAN,
		HAS_STRING BOOLEAN,
		STRING VARCHAR(60),
		FONT_NAME VARCHAR(60),
		FONT_SIZE SMALLINT,
		FONT_COLOR SMALLINT,
		FONT_STYLE SMALLINT,
		WIDTH SMALLINT
	);

CREATE TABLE GUI_ELEMENT_TYPES (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER,
		OWNER_PID INTEGER,
		RIGHTS SMALLINT,
		COMMIT_PID INTEGER,
		GUI_ELEMENT_TYPE_PID INTEGER NOT NULL,
		PLUGIN_PID SMALLINT,
				IS_CONTAINER BOOLEAN,
		HAS_STRING BOOLEAN,
		SWT_COMPONENT VARCHAR(60),
		SWT_TYPE VARCHAR(60),
		DFLT_STRING VARCHAR(60),
		DFLT_FONT_NAME VARCHAR(60),
		DFLT_FONT_SIZE SMALLINT,
		DFLT_FONT_COLOR SMALLINT,
		DFLT_FONT_STYLE SMALLINT,
		DFLT_WIDTH SMALLINT,
		DFLT_HEIGHT SMALLINT,
		MIN_WIDTH SMALLINT,
		MIN_HEIGHT SMALLINT
	);

CREATE TABLE SUBSETS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER,
		OWNER_PID INTEGER,
		RIGHTS SMALLINT,
		COMMIT_PID INTEGER,
		SUBSET_PID INTEGER NOT NULL,
				SUBSET_TYPE_KEY SMALLINT,
		SIZE INTEGER,
		STACK_INDEX INTEGER,
		IS_FIXED BOOLEAN
	);

CREATE TABLE SUBSET_TYPES (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER,
		OWNER_PID INTEGER,
		RIGHTS SMALLINT,
		COMMIT_PID INTEGER,
		SUBSET_TYPE_PID INTEGER NOT NULL,
				RECENT_MAX SMALLINT,
		FOCUS1_KEY SMALLINT,
		IS_ALL BOOLEAN,
		IS_SAME_TYPES BOOLEAN,
		IS_SAME_LINK BOOLEAN,
		FOCUS2_KEY SMALLINT,
		IS_MIXED BOOLEAN
	);

CREATE TABLE SUBSET_SINGLES (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER,
		OWNER_PID INTEGER,
		RIGHTS SMALLINT,
		COMMIT_PID INTEGER,
		SUBSET_SINGLE_PID INTEGER NOT NULL,
		SUBSET_PID INTEGER,
		USE_ORDER INTEGER,
		REFER_PID INTEGER
	);

CREATE TABLE SUBSET_PAIRS(
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER,
		OWNER_PID INTEGER,
		RIGHTS SMALLINT,
		COMMIT_PID INTEGER,
		SUBSET_PAIR_PID INTEGER NOT NULL,
		SUBSET_PID INTEGER,
		USE_ORDER INTEGER,
		REFER1_PID INTEGER,
		REFER2_PID INTEGER
	);

CREATE TABLE SUBSET_MIXES (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER,
		OWNER_PID INTEGER,
		RIGHTS SMALLINT,
		COMMIT_PID INTEGER,
		SUBSET_MIX_PID INTEGER NOT NULL,
		SUBSET_PID INTEGER,
		USE_ORDER INTEGER,
		REFER1_KEY SMALLINT,
		REFER1_PID INTEGER,
		REFER2_KEY SMALLINT,
		REFER2_PID INTEGER
	);

CREATE TABLE SUBSET_FILTER_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER,
		OWNER_PID INTEGER,
		RIGHTS SMALLINT,
		SUBSET_FILTER_DEFN_PID INTEGER NOT NULL,
		COMMIT_PID INTEGER,
		INPUT_TYPE_KEY SMALLINT,
		OUTPUT_TYPE_KEY SMALLINT,
		FILTER_START_PID SMALLINT
	);

CREATE TABLE SUBSET_FILTER_ORDERS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER,
		OWNER_PID INTEGER,
		RIGHTS SMALLINT,
		COMMIT_PID INTEGER,
		SUBSET_FILTER_ORDER_PID INTEGER NOT NULL,
		PREV_ALIAS_KEY INTEGER,
		THIS_ALIAS_KEY INTEGER,
		NEXT_ALIAS_KEY INTEGER
	);

CREATE TABLE SUBSET_FILTER_JOINS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER,
		OWNER_PID INTEGER,
		RIGHTS SMALLINT,
		COMMIT_PID INTEGER,
		SUBSET_JOIN_PID INTEGER NOT NULL,
		A_SUBSET_PID INTEGER,
		B_SUBSET_PID INTEGER,
		OPERATION_KEY INTEGER,
		IS_TEMP_RESULT BOOLEAN,
		RESULT_SUBSET_PID INTEGER
	);

CREATE TABLE SUBSET_FILTER_ACTIONS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER,
		OWNER_PID INTEGER,
		RIGHTS SMALLINT,
		COMMIT_PID INTEGER,
		SUBSET_ACTION_PID INTEGER NOT NULL,
		ACTION_KEY INTEGER,
		TARGET_OBJ_PID INTEGER,
		ACTION_HAS_PARAMS BOOLEAN,
		IS_TEMP_RESULT BOOLEAN,
		RESULT_SUBSET_PID INTEGER
	);

CREATE TABLE PERSONS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER,
		OWNER_PID INTEGER,
		RIGHTS SMALLINT,
		COMMIT_PID INTEGER,
		PERSON_PID INTEGER NOT NULL,
		PRIMARY_NAME_KEY SMALLINT,
		PRIMARY_NAME_PID INTEGER,
		PRMY_BIRTH_PID INTEGER,
		PRMY_DEATH_PID INTEGER,
		PRMY_FATHER_PID INTEGER,
		PRMY_MOTHER_PID INTEGER,
		HAS_EVENT_ASSOC BOOLEAN,
		HAS_TASK_ASSOC BOOLEAN,
		HAS_CHILDREN BOOLEAN,
		HAS_CITATIONS BOOLEAN,
		HAS_MANY_NAMES BOOLEAN
	);

CREATE TABLE PERSON_FLAGSETS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER,
		OWNER_PID INTEGER,
		RIGHTS SMALLINT,
		PERSON_FLAGSET_PID INTEGER NOT NULL,
		COMMIT_PID INTEGER,
		PARENT_OBJ_PID SMALLINT,
		F001 SMALLINT,
		F002 SMALLINT,
		F003 SMALLINT,
		F004 SMALLINT,
		F005 SMALLINT,
		F006 SMALLINT,
		F007 SMALLINT,
		F008 SMALLINT,
		F009 SMALLINT,
		F010 SMALLINT,
		F011 SMALLINT,
		F012 SMALLINT,
		F013 SMALLINT,
		F014 SMALLINT,
		F015 SMALLINT,
		F016 SMALLINT,
		F017 SMALLINT,
		F018 SMALLINT,
		F019 SMALLINT,
		F020 SMALLINT,
		F021 SMALLINT,
		F022 SMALLINT,
		F023 SMALLINT,
		F024 SMALLINT,
		F025 SMALLINT
	);

CREATE TABLE PERSON_NOTEPADS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER,
		OWNER_PID INTEGER,
		RIGHTS SMALLINT,
		COMMIT_PID INTEGER,
		PERSON_NOTEPAD_PID INTEGER NOT NULL,
		PARENT_PID INTEGER,
		NOTEPAD_DEFN_PID SMALLINT,
		NOTEPAD VARCHAR(32000)
	);

CREATE TABLE PERSON_NAMES (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER,
		OWNER_PID INTEGER,
		RIGHTS SMALLINT,
		COMMIT_PID INTEGER,
		PERSON_NAME_PID INTEGER NOT NULL,
		PARENT_PID INTEGER,
		NAME_STYLE_KEY SMALLINT,
		NAME_TAG_KEY SMALLINT,
		HDATE_PID SMALLINT,
		THEME_KEY SMALLINT,
		LOCAL_SENTCE_PID INTEGER,
		SENTCE_TYPE_KEY SMALLINT,
		HAS_MEMOS BOOLEAN,
		HDATE_INFERRED BOOLEAN
	);

CREATE TABLE PERSON_NAME_PARTS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER,
		OWNER_PID INTEGER,
		RIGHTS SMALLINT,
		COMMIT_PID INTEGER,
		PERSON_NAME_PART_PID INTEGER NOT NULL,
		EMELEMENT_PID SMALLINT,
		SHARED INTEGER,
		LANG_CODE VARCHAR(4),
		TRANS VARCHAR(160)
	);

CREATE TABLE PERSON_NAME_MAPS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER,
		OWNER_PID INTEGER,
		RIGHTS SMALLINT,
		COMMIT_PID INTEGER,
		PLUGIN_PID INTEGER,
		PERSON_NAME_MAP_PID INTEGER NOT NULL,
		PARENT_NAME_PID INTEGER,
		ELEMENT_ID SMALLINT,
		SHARED INTEGER
	);

CREATE TABLE PERSON_LIFE_LINKS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER,
		OWNER_PID INTEGER,
		RIGHTS SMALLINT,
		COMMIT_PID INTEGER,
		PERSON_LIFE_LINK_PID INTEGER NOT NULL,
		EVENT_PID INTEGER,
		BETWEEN_ASSOC_PID INTEGER,
		SUBJECT_PERSON_PID INTEGER,
		SUBJECT_ROLE_PID INTEGER,
		OTHER_PERSON_PID INTEGER,
		OTHER_ROLE_PID INTEGER,
		LAST_UPDATE TIMESTAMP
	);

CREATE TABLE EVENT_TAG_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER,
		OWNER_PID INTEGER,
		RIGHTS SMALLINT,
		COMMIT_PID INTEGER,
		EVENT_TAG_DEFN_PID INTEGER NOT NULL,
		REMINDER_PID SMALLINT,
		DFLT_GROUP_KEY SMALLINT,
		DFLT_THEME_KEY SMALLINT,
		TAG_RULE_KEY SMALLINT,
		SENTCE_TYPES_KEY SMALLINT,
		DFLT_SENTCE_PID INTEGER,
		MEMO_TYPES_KEY SMALLINT,
		ALLOW_LOCATION BOOLEAN,
		ALLOW_HDATE BOOLEAN,
		SHOW BOOLEAN
	);

CREATE TABLE EVENTS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER,
		OWNER_PID INTEGER,
		RIGHTS SMALLINT,
		COMMIT_PID INTEGER,
		EVENT_PID INTEGER NOT NULL,
		PARENT_PID INTEGER,
		SORT_ORDER SMALLINT,
		LOCATION_PID INTEGER,
		HDATE_PID INTEGER,
		TAG_TYPE_KEY SMALLINT,
		THEME_KEY SMALLINT,
		LOCAL_SENTCE_PID INTEGER,
		SENTCE_TYPE_KEY SMALLINT,
		HAS_MEMOS BOOLEAN,
		HDATE_INFERRED BOOLEAN,
		LOCATION_INFERRED BOOLEAN
	);

CREATE TABLE EVENT_ASSOC_TAG_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER,
		OWNER_PID INTEGER,
		RIGHTS SMALLINT,
		COMMIT_PID INTEGER,
		EVENT_ASSOC_TAG_DEFN_PID INTEGER NOT NULL,
		ASSOC_TYPE_KEY SMALLINT,
		ASSOC_SUB_TYPE_KEY SMALLINT,
		ASSOC_PID INTEGER,
		REMINDER_PID INTEGER,
		ROLE_NAME_KEY SMALLINT,
		SORT_ORDER SMALLINT,
		LIFE_PHASE_KEY SMALLINT,
		GROUP_KEY SMALLINT,
		THEME_KEY SMALLINT,
		TAG_RULE_KEY SMALLINT,
		GLOBAL_SENTCES_PID INTEGER,
		SHOW BOOLEAN
	);

CREATE TABLE EVENT_ASSOCS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER,
		OWNER_PID INTEGER,
		RIGHTS SMALLINT,
		COMMIT_PID INTEGER,
		EVENT_ASSOC_PID INTEGER NOT NULL,
		OBJECT_PROJECT_PID INTEGER,
		OBJECT_PID INTEGER,
		SORT_ORDER SMALLINT,
		PARENT_TYPE_KEY SMALLINT,
		PARENT_PID INTEGER,
		ASSOC_PROJECT_PID INTEGER,
		ASSOC_TYPE_KEY SMALLINT,
		ASSOC_TYPE_PID INTEGER,
		TAG_TYPE_KEY SMALLINT,
		THEME_KEY INTEGER,
		LOCAL_SENTCS_PID INTEGER,
		LOCAL_MEMOS_PID INTEGER
	);

CREATE TABLE EVENT_BTWN_ASSOC_TAG_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER,
		OWNER_PID INTEGER,
		RIGHTS SMALLINT,
		COMMIT_PID INTEGER,
		EVENT_BTWN_ASSOC_TAG_DEFN_PID INTEGER NOT NULL,
		OBJECT_KEY SMALLINT,
		ASSOC_A_TYPE_KEY SMALLINT,
		ASSOC_A_SUB_TYPE_KEY SMALLINT,
		ASSOC_A_TYPE_PID INTEGER,
		ASSOC_B_TYPE_KEY SMALLINT,
		ASSOC_B_SUB_TYPE_KEY SMALLINT,
		ASSOC_B_TYPE_PID INTEGER,
		REMINDER_PID INTEGER,
		ROLE_PAIR_PID SMALLINT,
		GROUP_KEY SMALLINT,
		THEME_KEY SMALLINT,
		TAG_RULE_KEY SMALLINT,
		A_SUBJ_SENTCS_PID INTEGER,
		B_SUBJ_SENTCS_PID INTEGER,
		SHOW BOOLEAN
	);

CREATE TABLE EVENT_BTWN_ASSOC_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER,
		OWNER_PID INTEGER,
		RIGHTS SMALLINT,
		COMMIT_PID INTEGER,
		EVENT_BTWN_ASSOC_PID INTEGER NOT NULL,
		EVENT_PARENT_PID INTEGER,
		EVENT_PROJECT_PID SMALLINT,
		EVENT_PID INTEGER,
		A_PROJECT_PID SMALLINT,
		A_ENTITY_TYPE_KEY SMALLINT,
		A_ENTITY_TYPE_PID INTEGER,
		B_PROJECT_PID SMALLINT,
		B_ENTITY_TYPE_KEY SMALLINT,
		B_ENTITY_TYPE_PID INTEGER,
		TAG_TYPE_KEY SMALLINT,
		THEME_KEY SMALLINT,
		A_B_SENTCS_PID INTEGER,
		B_A_SENTCS_PID INTEGER,
		LOCAL_MEMOS_PID INTEGER
	);

CREATE TABLE EVENT_TIMELINE_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER,
		OWNER_PID INTEGER,
		RIGHTS SMALLINT,
		COMMIT_PID INTEGER,
		EVENT_TIMELINE_DEFN_PID INTEGER NOT NULL,
		SHOW BOOLEAN
	);

CREATE TABLE EVENT_TIMELINE_ELMNTS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER,
		OWNER_PID INTEGER,
		RIGHTS SMALLINT,
		COMMIT_PID INTEGER,
		EVENT_TIMELINE_ELMNT_PID INTEGER NOT NULL,
		TIMELINE_PID SMALLINT,
		EVENT_PID INTEGER
	);

CREATE TABLE TASK_TAG_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER,
		OWNER_PID INTEGER,
		RIGHTS SMALLINT,
		COMMIT_PID INTEGER,
		TASK_TAG_DEFN_PID INTEGER NOT NULL,
		PARENT_PID INTEGER,
		SORT_ORDER SMALLINT,
		LOCATION_PID INTEGER,
		HDATE_PID INTEGER,
		TAG_TYPE_KEY SMALLINT,
		THEME_KEY SMALLINT,
		LOCAL_SENTCE_PID INTEGER,
		SENTCE_TYPE_KEY SMALLINT,
		HAS_MEMOS BOOLEAN,
		HDATE_INFERRED BOOLEAN,
		LOCATION_INFERRED BOOLEAN
	);

CREATE TABLE TASKS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER,
		OWNER_PID INTEGER,
		RIGHTS SMALLINT,
		COMMIT_PID INTEGER,
		TASK_PID INTEGER NOT NULL,
		PARENT_PID INTEGER,
		SORT_ORDER SMALLINT,
		LOCATION_PID INTEGER,
		HDATE_PID INTEGER,
		TAG_TYPE_KEY SMALLINT,
		THEME_KEY SMALLINT,
		LOCAL_SENTCE_PID INTEGER,
		SENTCE_TYPE_KEY SMALLINT,
		HAS_MEMOS BOOLEAN,
		HDATE_INFERRED BOOLEAN,
		LOCATION_INFERRED BOOLEAN
	);

CREATE TABLE TASK_ASSOC_TAG_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER,
		OWNER_PID INTEGER,
		RIGHTS SMALLINT,
		COMMIT_PID INTEGER,
		TASK_ASSOC_TAG_DEFN_PID INTEGER NOT NULL,
		ASSOC_TYPE_KEY SMALLINT,
		ASSOC_SUB_TYPE_KEY SMALLINT,
		ASSOC_PID INTEGER,
		REMINDER_PID INTEGER,
		ROLE_NAME_KEY SMALLINT,
		SORT_ORDER SMALLINT,
		LIFE_PHASE_KEY SMALLINT,
		GROUP_KEY SMALLINT,
		THEME_KEY SMALLINT,
		TAG_RULE_KEY SMALLINT,
		GLOBAL_SENTCES_PID INTEGER,
		SHOW BOOLEAN
	);

CREATE TABLE TASK_ASSOC_LINKS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER,
		OWNER_PID INTEGER,
		RIGHTS SMALLINT,
		COMMIT_PID INTEGER,
		TASK_ASSOC_LINK_PID INTEGER NOT NULL,
		OBJECT_PROJECT_PID INTEGER,
		OBJECT_PID INTEGER,
		SORT_ORDER SMALLINT,
		PARENT_TYPE_KEY SMALLINT,
		PARENT_PID INTEGER,
		ASSOC_PROJECT_PID INTEGER,
		ASSOC_TYPE_KEY SMALLINT,
		ASSOC_TYPE_PID INTEGER,
		TAG_TYPE_KEY SMALLINT,
		THEME_KEY SMALLINT,
		LOCAL_SENTCS_PID INTEGER,
		LOCAL_MEMOS_PID INTEGER
	);

CREATE TABLE TASK_BTWN_ASSOC_TAG_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER,
		OWNER_PID INTEGER,
		RIGHTS SMALLINT,
		COMMIT_PID INTEGER,
		TASK_BTWN_ASSOC_TAG_DEFN_PID INTEGER NOT NULL,
		OBJECT_KEY SMALLINT,
		ASSOC_A_TYPE_KEY SMALLINT,
		ASSOC_A_SUB_TYPE_KEY SMALLINT,
		ASSOC_A_TYPE_PID INTEGER,
		ASSOC_B_TYPE_KEY SMALLINT,
		ASSOC_B_SUB_TYPE_KEY SMALLINT,
		ASSOC_B_TYPE_PID INTEGER,
		REMINDER_PID SMALLINT,
		ROLE_PAIR_PID SMALLINT,
		GROUP_KEY SMALLINT,
		THEME_KEY SMALLINT,
		TAG_RULE_KEY SMALLINT,
		A_SUBJ_SENTCS_PID INTEGER,
		B_SUBJ_SENTCS_PID INTEGER,
		SHOW BOOLEAN
	);

CREATE TABLE TASK_BTWN_ASSOC_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER,
		OWNER_PID INTEGER,
		RIGHTS SMALLINT,
		COMMIT_PID INTEGER,
		TASK_BTWN_ASSOC_PID INTEGER NOT NULL,
		TASK_PARENT_PID INTEGER,
		TASK_PROJECT_PID SMALLINT,
		TASK_PID INTEGER,
		A_PROJECT_PID SMALLINT,
		A_ENTITY_TYPE_KEY SMALLINT,
		A_ENTITY_TYPE_PID INTEGER,
		B_PROJECT_PID SMALLINT,
		B_ENTITY_TYPE_KEY SMALLINT,
		B_ENTITY_TYPE_PID INTEGER,
		TAG_TYPE_KEY SMALLINT,
		THEME_KEY SMALLINT,
		A_B_SENTCS_PID INTEGER,
		B_A_SENTCS_PID INTEGER,
		LOCAL_MEMOS_PID INTEGER
	);

CREATE TABLE TASK_TIMELINE_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER,
		OWNER_PID INTEGER,
		RIGHTS SMALLINT,
		COMMIT_PID INTEGER,
		TASK_TIMELINE_DEFN_PID INTEGER NOT NULL,
		SHOW BOOLEAN
	);

CREATE TABLE TASK_TIMELINE_ELMNTS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER,
		OWNER_PID INTEGER,
		RIGHTS SMALLINT,
		COMMIT_PID INTEGER,
		TASK_TIMELINE_ELMNT_PID INTEGER NOT NULL,
		TIMELINE_PID SMALLINT,
		TASK_PID INTEGER
	);

CREATE TABLE LOCATIONS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		LOCATIONS_PID INTEGER NOT NULL,
		VISIBLE_ID INTEGER,
		OWNER_PID INTEGER,
		RIGHTS SMALLINT,
		COMMIT_PID INTEGER,
		LOCATION_PID INTEGER NOT NULL,
		PRMY_LOCN_PID INTEGER,
		HAS_CITATIONS BOOLEAN,
		HAS_MANY_NAMES BOOLEAN
	);

CREATE TABLE LOCATION_NAMES (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER,
		OWNER_PID INTEGER,
		RIGHTS SMALLINT,
		COMMIT_PID INTEGER,
		LOCATION_NAME_PID INTEGER NOT NULL,
		PARENT_PID INTEGER,
		NAME_TAG_KEY SMALLINT,
		NAME_STYLE_KEY SMALLINT,
		HDATE_PID INTEGER,
		THEME_KEY SMALLINT,
		LOCAL_SENTCE_PID INTEGER,
		SENTCE_TYPE_KEY SMALLINT,
		HAS_MEMOS BOOLEAN,
		HDATE_INFERRED BOOLEAN
	);

CREATE TABLE LOCATION_NAME_PARTS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER,
		OWNER_PID INTEGER,
		RIGHTS SMALLINT,
		COMMIT_PID INTEGER,
		LOCATION_NAME_PART_PID INTEGER NOT NULL,
		ELEMENT_PID SMALLINT,
		SHARED INTEGER,
		LANG_CODE VARCHAR(4),
		TRANS VARCHAR(160)
	);

CREATE TABLE LOCATION_NAME_MAPS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER,
		OWNER_PID INTEGER,
		RIGHTS SMALLINT,
		COMMIT_PID INTEGER,
		PLUGIN_PID INTEGER,
		LOCATION_NAME_MAP_PID INTEGER NOT NULL,
		PARENT_NAME_PID INTEGER,
		ELEMENT_PID SMALLINT,
		SHARED INTEGER
	);

CREATE TABLE LOCN_REPOS_LINKS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER,
		OWNER_PID INTEGER,
		RIGHTS SMALLINT,
		COMMIT_PID INTEGER,
		LOCN_REPOS_LINK_PID INTEGER NOT NULL,
		LOCATION_PID INTEGER,
		REPOSITORY_PID INTEGER,
		REP_LOCN_SENTCE_PID INTEGER,
		REP_LOCN_MEMOS_PID INTEGER,
		HAS_CITATIONS BOOLEAN
	);

CREATE TABLE SOURCES (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER,
		OWNER_PID INTEGER,
		RIGHTS SMALLINT,
		COMMIT_PID INTEGER,
		SOURCE_PID INTEGER NOT NULL,
		PRMY_NAME_PID INTEGER,
		SRC_MEMOS_PID INTEGER,
		SRC_SURETY VARCHAR(10),
		HAS_MANY_NAMES BOOLEAN
	);

CREATE TABLE SOURCE_NAMES (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER,
		OWNER_PID INTEGER,
		RIGHTS SMALLINT,
		COMMIT_PID INTEGER,
		SOURCE_NAME_PID INTEGER NOT NULL,
		PARENT_PID INTEGER,
		NAME_TAG_KEY SMALLINT,
		NAME_TAG_STYLE SMALLINT,
		HDATE_PID INTEGER,
		THEME_KEY SMALLINT,
		LOCAL_SENTCE_PID INTEGER,
		SENTCE_TYPE_KEY SMALLINT,
		HAS_MEMOS BOOLEAN,
		HDATE_INFERRED BOOLEAN
	);

CREATE TABLE SOURCE_NAME_PARTS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER,
		OWNER_PID INTEGER,
		RIGHTS SMALLINT,
		COMMIT_PID INTEGER,
		SOURCE_NAME_PART_PID INTEGER NOT NULL,
		ELEMENT_PID SMALLINT,
		SHARED INTEGER,
		LANG_CODE VARCHAR(4),
		TRANS VARCHAR(160)
	);

CREATE TABLE SOURCE_NAME_MAPS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER,
		OWNER_PID INTEGER,
		RIGHTS SMALLINT,
		COMMIT_PID INTEGER,
		SOURCE_NAME_MAP_PID INTEGER NOT NULL,
		PARENT_NAME_PID INTEGER,
		ELEMENT_PID SMALLINT,
		SHARED INTEGER
	);

CREATE TABLE SRC_SRC_TAG_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER,
		OWNER_PID INTEGER,
		RIGHTS SMALLINT,
		COMMIT_PID INTEGER,
		SRC_SRC_TAG_DEFN_PID INTEGER NOT NULL,
		SRC_SRC_TAG_KEY SMALLINT,
		REMINDER_PID SMALLINT,
		TAG_RULE_KEY SMALLINT,
		SHOW BOOLEAN
	);

CREATE TABLE SRC_SRC_LINKS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER,
		OWNER_PID INTEGER,
		RIGHTS SMALLINT,
		COMMIT_PID INTEGER,
		SRC_SRC_LINK_PID INTEGER NOT NULL,
		SOURCE1_PID INTEGER,
		SOURCE2_PID INTEGER,
		SRC_SRC_TAG_KEY SMALLINT,
		HAS_CITATIONS BOOLEAN
	);

CREATE TABLE SRC_REPOS_TAG_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER,
		OWNER_PID INTEGER,
		RIGHTS SMALLINT,
		COMMIT_PID INTEGER,
		SRC_REPOS_TAG_DEFN_PID INTEGER NOT NULL,
		SRC_RPOS_TAG_KEY SMALLINT,
		REMINDER_PID SMALLINT,
		TAG_RULE_KEY SMALLINT,
		SHOW BOOLEAN
	);

CREATE TABLE SRC_REPOS_LINKS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER,
		OWNER_PID INTEGER,
		RIGHTS SMALLINT,
		COMMIT_PID INTEGER,
		SRC_REPOS_LINK_PID INTEGER NOT NULL,
		SOURCE_PID INTEGER,
		REPOSITORY_PID INTEGER,
		SRC_REP_TAG_KEY SMALLINT,
		HAS_CITATIONS BOOLEAN
	);

CREATE TABLE CITATION_TAG_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER,
		OWNER_PID INTEGER,
		RIGHTS SMALLINT,
		COMMIT_PID INTEGER,
		CITATION_TAG_DEFN_PID INTEGER NOT NULL,
				ATTACH_TO_TYPE_KEY SMALLINT,
		REMINDER_PID SMALLINT,
		CITN_TAG_RULE_PID SMALLINT,
		SHOW BOOLEAN
	);

CREATE TABLE CITATIONS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER,
		OWNER_PID INTEGER,
		RIGHTS SMALLINT,
		COMMIT_PID INTEGER,
		CITATION_PID INTEGER NOT NULL,
		ATTACH_TO_KEY SMALLINT,
		ATTACH_TO_PID INTEGER,
		SOURCE_PID INTEGER,
		CITN_TAG_KEY SMALLINT,
		CITN_MEMOS_PID INTEGER,
		CITN_SURETY VARCHAR(10)
	);

CREATE TABLE HDATES (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER,
		OWNER_PID INTEGER,
		RIGHTS SMALLINT,
		COMMIT_PID INTEGER,
		HDATE_PID INTEGER NOT NULL,
		HDATE1 BIGINT,
		HDATE2 BIGINT,
		SORT_HDATE1 BIGINT,
		SORT_HDATE2 BIGINT,
		ORIGINAL_TEXT VARCHAR(160),
		LANG_CODE VARCHAR(4),
		HDATE_TYPE_KEY SMALLINT,
		HDATE_MEMOS_PID INTEGER,
		HDATE_SURETY VARCHAR(10),
		HAS_CITATIONS BOOLEAN
	);

CREATE TABLE HDATE_DATE_TYPES (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER,
		OWNER_PID INTEGER,
		RIGHTS SMALLINT,
		COMMIT_PID INTEGER,
		HDATE_DATE_TYPE_PID INTEGER NOT NULL,
		ORIGINAL_CALENDAR_KEY SMALLINT,
		WHEN_WRITTEN SMALLINT,
		WHERE_WRITTEN VARCHAR(160),
		CAL_CHNG_START_YEAR SMALLINT,
		CAL_CHNG_START_DAY SMALLINT,
		CAL_CHNG_END_YEAR SMALLINT,
		CAL_CHNG_END_DAY SMALLINT,
		DAYS_LOST SMALLINT,
		USED_OLD_STYLE BOOLEAN
	);

CREATE TABLE IMAGES (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER,
		OWNER_PID INTEGER,
		RIGHTS SMALLINT,
		COMMIT_PID INTEGER,
		IMAGE_PID INTEGER NOT NULL,
		IMAGE_SURETY VARCHAR(10),
		FILE_PATH VARCHAR(300),
		ENCODING_KEY SMALLINT,
		IMAGE_WIDTH SMALLINT,
		IMAGE_HEIGHT SMALLINT,
		IMAGE_HDATE_PID INTEGER
	);

CREATE TABLE EXTERNAL_FILES (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER,
		OWNER_PID INTEGER,
		RIGHTS SMALLINT,
		COMMIT_PID INTEGER,
		EXTERNAL_FILE_PID INTEGER NOT NULL,
		EXT_FILE_SURETY VARCHAR(10),
		FILE_PATH VARCHAR(300),
		ENCODING_KEY SMALLINT
	);

CREATE TABLE INTERNAL_TEXTS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER,
		OWNER_PID INTEGER,
		RIGHTS SMALLINT,
		COMMIT_PID INTEGER,
		INTERNAL_TEXT_PID INTEGER NOT NULL,
		INTL_TEXT_SURETY VARCHAR(10),
		ENCODING_KEY SMALLINT,
		TEXT CLOB(2147483647)
	);

CREATE TABLE SUBSTN_ALIASES (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER,
		OWNER_PID INTEGER,
		RIGHTS SMALLINT,
		COMMIT_PID INTEGER,
		SUBSTN_ALIAS_PID INTEGER NOT NULL,
		IS_DATA_ALIAS BOOLEAN,
		IS_COMPLETE BOOLEAN,
		FOR_SUBSETS BOOLEAN,
		HEAD_TYPE_KEY INTEGER,
		TAIL_TYPE_KEY INTEGER,
		IS_TEST_ALIAS BOOLEAN,
		IS_DATA_HEAD BOOLEAN,
		IS_DATA_TAIL BOOLEAN,
		PARENT_TYPE_KEY SMALLINT,
		THIS_TYPE_KEY SMALLINT,
		NAME_STYLE_KEY SMALLINT
	);

CREATE TABLE SUBSTN_ALIAS_TRANS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER,
		OWNER_PID INTEGER,
		RIGHTS SMALLINT,
		COMMIT_PID INTEGER,
		SUBSTN_ALIAS_TRAN_PID INTEGER NOT NULL,
		RECORD_PID INTEGER,
		LANG_CODE VARCHAR(4),
		RECIPE VARCHAR(300)
	);

CREATE TABLE SUBSTN_LABEL_TRANS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER,
		OWNER_PID INTEGER,
		RIGHTS SMALLINT,
		COMMIT_PID INTEGER,
		SUBSTN_LABEL_TRAN_PID INTEGER NOT NULL,
		TABLE_KEY SMALLINT,
		RECORD_PID INTEGER,
		LANG_CODE VARCHAR(4),
		NAME VARCHAR(160),
		DESCRIPTION VARCHAR(300),
		ABBREV VARCHAR(60)
	);

CREATE TABLE SUBSTN_STYLE_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER,
		OWNER_PID INTEGER,
		RIGHTS SMALLINT,
		COMMIT_PID INTEGER,
		SUBSTN_STYLE_DEFN_PID INTEGER NOT NULL,
		STYLE_LABEL_KEY SMALLINT
	);

CREATE TABLE SUBSTN_PARAM_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		SUBSTN_PARAM_DEFNS_PID INTEGER NOT NULL,
		VISIBLE_ID INTEGER,
		OWNER_PID INTEGER,
		RIGHTS SMALLINT,
		COMMIT_PID INTEGER,
		SUBSTN_PARAM_DEFN_PID INTEGER NOT NULL,
		PARENT_SUBSTN_PID INTEGER,
		PARAM_TYPE_KEY SMALLINT,
		PARAM_VALUE VARCHAR(100),
		DEFLT_VALUE VARCHAR(100)
	);

CREATE TABLE SUBSTN_TEST_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER,
		OWNER_PID INTEGER,
		RIGHTS SMALLINT,
		COMMIT_PID INTEGER,
		SUBSTN_TEST_DEFN_PID INTEGER NOT NULL,
		PARENT_TYPE_KEY SMALLINT,
		ACTION_KEY SMALLINT,
		ARG1_KEY SMALLINT,
		ARG2_KEY SMALLINT
	);

CREATE TABLE SUBSTN_ACTION_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		VISIBLE_ID INTEGER,
		OWNER_PID INTEGER,
		RIGHTS SMALLINT,
		COMMIT_PID INTEGER,
		SUBSTN_ACTION_DEFN_PID INTEGER NOT NULL,
		PARENT_TYPE_KEY SMALLINT,
		ACTION_HAS_2_ARGS BOOLEAN,
		ACTION_HAS_PARAMS BOOLEAN
	);

CREATE TABLE SUBSTN_DATA_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		DEFN_PID SMALLINT NOT NULL,
		SUBSTN_DATA_DEFNS_PID INTEGER NOT NULL,
		VISIBLE_ID INTEGER,
		OWNER_PID INTEGER,
		RIGHTS SMALLINT,
		COMMIT_PID INTEGER,
		SUBSTN_DATA_DEFN_PID INTEGER NOT NULL,
		IS_COMPLETE BOOLEAN,
		HEAD_TYPE_KEY SMALLINT,
		TAIL_TYPE_KEY SMALLINT,
		IS_DATA_HEAD BOOLEAN,
		IS_DATA_TAIL BOOLEAN,
		PARENT_TYPE_KEY SMALLINT,
		THIS_TYPE_KEY SMALLINT,
		ARG1_TYPE_KEY SMALLINT,
		ARG2_IS_CONSTANT BOOLEAN,
		IS_RUN_TIME_ASK BOOLEAN,
		ASK_QUESTION_PID INTEGER,
		ARG2_VALUE VARCHAR(160)
	);

