CREATE VIEW PUBLIC.SAMPLE_VIEW AS
SELECT PUBLIC.SUBSTN_PARAM_NAMES.SUBSTN_PARAM_NAME_PID, PUBLIC.SUBSTN_PARAM_NAMES.VIEW_DATA_SCRIPT_GROUP_KEY,
  PUBLIC.SUBSTN_PARAM_NAMES.VIEW_DATA_SCRIPT_PID, PUBLIC.SUBSTN_PARAM_NAMES.MODIFY_DATA_SCRIPT_GROUP_KEY,
  PUBLIC.SUBSTN_PARAM_NAMES.MODIFY_DATA_SCRIPT_PID, PUBLIC.SUBSTN_PARAM_NAMES.DELETE_DATA_SCRIPT_GROUP_KEY,
  PUBLIC.SUBSTN_PARAM_NAMES.DELETE_DATA_SCRIPT_PID, PUBLIC.SUBSTN_PARAM_NAMES.DEFLT_VALUE,
  PUBLIC.SUBSTN_PARAM_NAMES.MUST_BE_ENTERED, PUBLIC.SUBSTN_PARAM_NAMES.DATA_TYPE_KEY,
  PUBLIC.SUBSTN_PARAM_NAMES.PARAM_SET_KEY, PUBLIC.SUBSTN_PARAM_NAMES.EVAL_DATA_SCRIPT_PID,
  PUBLIC.SUBSTN_PARAM_NAMES.EVAL_DATA_SCRIPT_GROUP_KEY, PUBLIC.SUBSTN_PARAM_VALUES.SUBSTN_PARAM_VALUE_PID,
  PUBLIC.SUBSTN_PARAM_VALUES.PARENT_STEP_PID, PUBLIC.SUBSTN_PARAM_VALUES.PARAM_LIST_KEY,
  PUBLIC.SUBSTN_PARAM_VALUES.PARAM_NAME_KEY,
  PUBLIC.SUBSTN_PARAM_VALUES.VALUE_IS_DATA_ALIAS, PUBLIC.SUBSTN_PARAM_VALUES.VALUE_IS_OTHER_ALIAS,
  PUBLIC.SUBSTN_PARAM_VALUES.ALIAS_KEY, PUBLIC.SUBSTN_PARAM_VALUES.DEFLT_PARAM_STEP_PID
  FROM PUBLIC.SUBSTN_PARAM_NAMES, PUBLIC.SUBSTN_PARAM_VALUES
  WHERE PUBLIC.SUBSTN_PARAM_NAMES.PARAM_SET_KEY = PUBLIC.SUBSTN_PARAM_VALUES.PARAM_SET_KEY;

