--<ScriptOptions statementTerminator=";"/>

ALTER TABLE PERSON DROP CONSTRAINT PERSON_PK;

DROP INDEX PERSON_PER_NO_IDX;

DROP INDEX PRIMARY_KEY_8;

DROP INDEX PRIMARY_KEY_8C;

DROP TABLE PERSON;

CREATE TABLE PERSON (
		PER_NO INTEGER NOT NULL,
		FATHER INTEGER,
		MOTHER INTEGER,
		LAST_EDIT DATE,
		DSID INTEGER NOT NULL,
		REF_ID INTEGER,
		REFERENCE CHAR(12),
		SPOULAST INTEGER,
		SCBUFF CHAR(10),
		PBIRTH CHAR(30),
		PDEATH CHAR(30),
		SEX CHAR(1),
		LIVING CHAR(1),
		BIRTHORDER CHAR(2),
		MULTIBIRTH CHAR(1),
		ADOPTED CHAR(1),
		ANCE_INT CHAR(1),
		DESC_INT CHAR(1),
		RELATE INTEGER,
		RELATEFO INTEGER,
		TT CHAR(1),
		FLAG1 CHAR(1),
		FLAG2 CHAR(1),
		FLAG3 CHAR(1),
		FLAG4 CHAR(1),
		FLAG5 CHAR(1),
		FLAG6 CHAR(1),
		FLAG7 CHAR(1),
		FLAG8 CHAR(1),
		FLAG9 CHAR(1),
				FLAG10 CHAR(1),
				FLAG11 CHAR(1),
		FLAG12 CHAR(1),
		FLAG13 CHAR(1),
		FLAG14 CHAR(1),
		FLAG15 CHAR(1),
		FLAG16 CHAR(1),
		FLAG17 CHAR(1),
		FLAG18 CHAR(1),
		FLAG19 CHAR(1)
	);

CREATE UNIQUE INDEX PERSON_PER_NO_IDX ON PERSON (PER_NO ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_8 ON PERSON (PER_NO ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_8C ON PERSON (PER_NO ASC);

ALTER TABLE PERSON ADD CONSTRAINT PERSON_PK PRIMARY KEY (PER_NO);

