--<ScriptOptions statementTerminator=";"/>

DROP TABLE USER_TYPES;

DROP TABLE DATA_60_DICT_TRANS;

DROP TABLE EVENT_TAG_DEFNS;

DROP TABLE NOTEPAD_DEFNS;

DROP TABLE GUI_60_DICT_TRANS;

DROP TABLE SUBSET_PAIRS;

DROP TABLE SOURCE_NAMES;

DROP TABLE GUI_LANGUAGE_NAMES;

DROP TABLE USER_GROUPS;

DROP TABLE TAG_GROUP_DEFNS;

DROP TABLE FIELD_DEFNS;

DROP TABLE GUI_400_DICT_TRANS;

DROP TABLE DISPLAY_TYPES;

DROP TABLE REMINDER_TRANS;

DROP TABLE SOURCE_NAME_PARTS;

DROP TABLE TASK_TIMELINE_DEFNS;

DROP TABLE DATA_20_DICT_TRANS;

DROP TABLE ENTITY_NAME_TAG_DEFNS;

DROP TABLE TAG_RULE_DEFNS;

DROP TABLE ROLE_PAIR_NAME_TRANS;

DROP TABLE OUTPUT_TEMPLATE_TRANS;

DROP TABLE NAMED_MEMO_TRANS;

DROP TABLE PUBLISH_TYPE_TRANS;

DROP TABLE CITATION_TAG_DEFNS;

DROP TABLE LOCATION_NAMES;

DROP TABLE SRC_SRC_LINKS;

DROP TABLE PERSON_NAMES;

DROP TABLE TEMPLATE_TYPE_DEFNS;

DROP TABLE SCHEMA_DEFNS;

DROP TABLE MESSAGES_TRANS;

DROP TABLE SENTENCE_TYPE_DEFNS;

DROP TABLE NAME_TEMPLATE_TYPES;

DROP TABLE SRC_REPOS_LINKS;

DROP TABLE LOCATION_NAME_PARTS;

DROP TABLE SUBSETS;

DROP TABLE GUI_ELEMENT_SETTINGS;

DROP TABLE FIELD_FORMATS;

DROP TABLE ROLE_NAME_TRANS;

DROP TABLE INDEX_DEFNS;

DROP TABLE EVENT_BTWN_ASSOC_TAG_DEFNS;

DROP TABLE VIEWPOINT_ELEMENTS;

DROP TABLE SUBSET_MIXES;

DROP TABLE NAME_ELMNT_TYPE_DEFNS;

DROP TABLE EVENT_TIMELINE_DEFNS;

DROP TABLE PERSONS;

DROP TABLE COMMIT_LOGS;

DROP TABLE SESSIONS;

DROP TABLE USERS;

DROP TABLE EVENT_ASSOCS;

DROP TABLE SOURCE_NAME_MAPS;

DROP TABLE EXTERNAL_FILES;

DROP TABLE SUBSET_FILTER_ORDERS;

DROP TABLE SUBSTN_DATA_DEFNS;

DROP TABLE TASK_ASSOC_LINKS;

DROP TABLE TASKS;

DROP TABLE HDATE_DATE_TYPES;

DROP TABLE GUI_MAPPED_TRANS;

DROP TABLE SUBSET_TYPES;

DROP TABLE FLAG_STATE_DEFNS;

DROP TABLE LOCATION_NAME_MAPS;

DROP TABLE COMMIT_ITEMS;

DROP TABLE LANGUAGES;

DROP TABLE FIELD_DATA_TYPES;

DROP TABLE SUBSTN_ACTION_DEFNS;

DROP TABLE SRC_REPOS_TAG_DEFNS;

DROP TABLE GUI_SCREENS;

DROP TABLE SOURCES;

DROP TABLE PERSON_LIFE_LINKS;

DROP TABLE FLAG_DEFNS;

DROP TABLE ENTITY_TAG_DEFNS;

DROP TABLE LOCN_REPOS_LINKS;

DROP TABLE EVENTS;

DROP TABLE SUBSTN_LABEL_TRANS;

DROP TABLE LANGUAGE_NAME_TRANS;

DROP TABLE IMAGES;

DROP TABLE SUBSET_FILTER_DEFNS;

DROP TABLE DATA_400_DICT_TRANS;

DROP TABLE GUI_160_DICT_TRANS;

DROP TABLE TASK_BTWN_ASSOC_TAG_DEFNS;

DROP TABLE PROJECTS;

DROP TABLE LOCATIONS;

DROP TABLE GUI_LANGUAGES;

DROP TABLE SUBSET_FILTER_ACTIONS;

DROP TABLE SUBSTN_ALIAS_TRANS;

DROP TABLE SUBSET_SINGLES;

DROP TABLE TABLE_DEFNS;

DROP TABLE HDATES;

DROP TABLE RECORD_VALIDS;

DROP TABLE ENCODING_TYPE_DEFNS;

DROP TABLE GUI_20_DICT_TRANS;

DROP TABLE NAMED_MEMO_TYPES;

DROP TABLE NAME_STYLE_TYPE_DEFNS;

DROP TABLE EVENT_ASSOC_TAG_DEFNS;

DROP TABLE PLUGINS;

DROP TABLE USER_MESSAGES;

DROP TABLE FIELD_RECENTS;

DROP TABLE GUI_SCREEN_CONFIGS;

DROP TABLE NAME_ELMNT_INPUT_DEFNS;

DROP TABLE PERSON_NAME_PARTS;

DROP TABLE TASK_TIMELINE_ELMNTS;

DROP TABLE PACKAGES;

DROP TABLE SRC_SRC_TAG_DEFNS;

DROP TABLE FIELD_TYPES;

DROP TABLE GUI_ELEMENTS;

DROP TABLE TASK_ASSOC_TAG_DEFNS;

DROP TABLE LANGUAGE_USES;

DROP TABLE TASK_BTWN_ASSOC_DEFNS;

DROP TABLE PROJECT_SERVERS;

DROP TABLE PERSON_NOTEPADS;

DROP TABLE DATA_160_DICT_TRANS;

DROP TABLE LABEL_TRANS;

DROP TABLE VIEWPOINT_CONFIGS;

DROP TABLE NAME_OUT_TEMPLATES;

DROP TABLE INTERNAL_TEXTS;

DROP TABLE TASK_TAG_DEFNS;

DROP TABLE SUBSET_FILTER_JOINS;

DROP TABLE GUI_ELEMENT_TYPES;

DROP TABLE FIELD_VALIDS;

DROP TABLE EVENT_BTWN_ASSOC_DEFNS;

DROP TABLE PERSON_NAME_MAPS;

DROP TABLE SUBSTN_PARAM_DEFNS;

DROP TABLE SUBSTN_TEST_DEFNS;

DROP TABLE CITATIONS;

DROP TABLE LIFE_PHASE;

DROP TABLE SUBSTN_STYLE_DEFNS;

DROP TABLE SUBSTN_ALIASES;

DROP TABLE PERSON_FLAGSETS;

DROP TABLE EVENT_TIMELINE_ELMNTS;

DROP TABLE THEME_DEFNS;

DROP TABLE SENTENCE_TRANS;

