--<ScriptOptions statementTerminator=";"/>

DROP VIEW "PUBLIC"."TEMPLATE_VIEW";

CREATE VIEW "PUBLIC"."TEMPLATE_VIEW" (RECORD_NUM, SET_KEY, COMMIT_PID, PHYSICAL_NAME_PART_PID, ELEMENT_PID, THIS_NAME_EVENT_PID, NEXT_NAME_EVENT_PID, SHARED, LANG_CODE, TRANS) 
WITH CASCADED CHECK OPTION;

