CREATE VIEW EVENTVIEW AS SELECT EVENT.ETYPE, EVENT.EDATE, EVENT.PLACENUM, EVENT.EFOOT, TAGTYPE.ETYPENAME, 
   PLACEPARTVALUE.UID, PLACEPARTVALUE.TYPE, PLACEDICTIONARY.XVALUE, EVENT.PER1, EVENT.PER2
   FROM EVENT, TAGTYPE, PLACEPARTVALUE, PLACEDICTIONARY    
   WHERE  TAGTYPE.ETYPENUM = EVENT.ETYPE    
   AND PLACEPARTVALUE.RECNO = EVENT.PLACENUM
   AND PLACEDICTIONARY.UID = EVENT.PLACENUM    
   ORDER BY EVENT.EDATE, PLACEPARTVALUE.TYPE;