SELECT EVENT.ETYPE, EVENT.EDATE, EVENT.PLACENUM, EVENT.EFOOT,
  TAGTYPE.ETYPENAME, PLACEPARTVALUE.UID, PLACEPARTVALUE.TYPE, PLACEDICTIONARY.XVALUE
  FROM EVENT, TAGTYPE, PLACEPARTVALUE, PLACEDICTIONARY
  WHERE (EVENT.PER1 = 5 OR EVENT.PER2 = 5) AND TAGTYPE.ETYPENUM = EVENT.ETYPE
  AND PLACEPARTVALUE.RECNO = EVENT.PLACENUM
  AND PLACEDICTIONARY.UID = EVENT.PLACENUM
  ORDER BY EVENT.EDATE, PLACEPARTVALUE.TYPE;
